export enum apiKeys {
  mainSprints = "main-sprints",
  cases = "cases",
  ourTeam = "our-team",
  partners = "partners",
  media = "media",
  events = "events",
  upcomingEvents = "upcoming-events",
  caseCategories = "case-categories",
  research = "research",
  clubBanner = "club-banner",
  companyValues = "company-values",
  expertsFocusing = "experts-focusing",
  clubImages = "club-images",
  mediaImages = "media-images",
}
